enum BashTheme
{
    BASH_NORMAL = 0,
    BASH_BOLD = 1,
    BASH_DIM = 2,
    BASH_ITALIC = 3,
    BASH_UNDERLINE = 4,
    BASH_BLINK = 5,
    BASH_INVISIBLE = 8,
    BASH_STRIKETHROUGH = 9,
    BASH_DOUBLEUNDERLINE = 21,
    BASH_OVERLINE = 53,

    BASH_DARK_BLACK_BLACK = 30,
    BASH_DARK_RED_BLACK = 31,
    BASH_DARK_GREEN_BLACK = 32,
    BASH_DARK_YELLOW_BLACK = 33,
    BASH_DARK_BLUE_BLACK = 34,
    BASH_DARK_PURPLE_BLACK = 35,
    BASH_DARK_CYAN_BLACK = 36,
    BASH_DARK_WHITE_BLACK = 37,

    BASH_WHITE_DARK_BLACK = 40,
    BASH_WHITE_DARK_RED = 41,
    BASH_WHITE_DARK_GREEN = 42,
    BASH_WHITE_DARK_YELLOW = 43,
    BASH_WHITE_DARK_BLUE = 44,
    BASH_WHITE_DARK_PURPLE = 45,
    BASH_WHITE_DARK_CYAN = 46,
    BASH_WHITE_DARK_WHITE = 47,

    BASH_BRIGHT_BLACK_BLACK = 90,
    BASH_BRIGHT_RED_BLACK = 91,
    BASH_BRIGHT_GREEN_BLACK = 92,
    BASH_BRIGHT_YELLOW_BLACK = 93,
    BASH_BRIGHT_BLUE_BLACK = 94,
    BASH_BRIGHT_PURPLE_BLACK = 95,
    BASH_BRIGHT_CYAN_BLACK = 96,
    BASH_BRIGHT_WHITE_BLACK = 97,

    BASH_WHITE_BRIGHT_BLACK = 100,
    BASH_WHITE_BRIGHT_RED = 101,
    BASH_WHITE_BRIGHT_GREEN = 102,
    BASH_WHITE_BRIGHT_YELLOW = 103,
    BASH_WHITE_BRIGHT_BLUE = 104,
    BASH_WHITE_BRIGHT_PURPLE = 105,
    BASH_WHITE_BRIGHT_CYAN = 106,
    BASH_WHITE_BRIGHT_WHITE = 107,
};

void setESC(int theme);
void applyDesign(char *design);
char* hyperLink(char *link, char *title);
void rgb(int r, int g, int b, bool background);